### ISSUE TITLE
unzip your mods content

### ISSUE THREAD

**Issue by SimonWoodburyForget** [MisterCinnabar/Revenge-Of-The-Data-Mod#1]
Content of Github repositories must be decompressed for the game to pick them up from Github.

**Comment by MisterCinnabar** [comment]
Alright, I'll try fixing that.

**Comment by MisterCinnabar** [comment]
It won't let me post the folders I have. But the issue is that I'm on mobile, not on desktop

**Comment by SimonWoodburyForget** [comment]
You should be pushing your files to Github with Git, a version control tool. If you're on a mobile you wont be able to easily do that, because mobile isn't a platform you should be developing *anything* from, and Git is a *development* tool.

Regardless of that, you should be able to upload files, albeit I have never tried to do so.

**Comment by MisterCinnabar** [comment]
It has been finally done.
I had to wait over a month before I got onto a good computer.
